### ISSUE TITLE
Project can't be used as a dependency

### ISSUE THREAD

**Issue by hooperben** [eigerco/celestia-node-rs#37]
Hello!

When trying to use the methods in this library (specifically src/rpc/) as a dependency - and then running `cargo build` | `cargo c` | `cargo run`, the build fails.

Steps to reproduce:
1. Create a new rust project
2. Add this project as a dependency i.e
```
# celestia rust dependency
celestia-rust = { git = "https://github.com/eigerco/celestia-node-rs", default-features = false }
```

3. run any build/compilation step and the build will fail with a serialization error like so:
<img width="1257" alt="image" src="https://github.com/eigerco/celestia-node-rs/assets/99215416/3572ee7b-7078-41c1-9720-67e07a4d00d8">

Any help would be awesome - thank you.

**Comment by oblique** [comment]
We are currently using patching method for the tendermint dependency. So you need to do the same:

```toml
[dependencies]
celestia-rpc = { git = "https://github.com/eigerco/celestia-node-rs", default-features = false }

[patch.crates-io]
tendermint = { git = "https://github.com/eigerco/celestia-tendermint-rs.git", rev = "dbb4434" }
tendermint-proto = { git = "https://github.com/eigerco/celestia-tendermint-rs.git", rev = "dbb4434" }
```

The main benefit of the above is that you can use any other crate from crates.io and still works with our fork, but we can change it.

**Comment by oblique** [comment]
Opened PR https://github.com/eigerco/celestia-node-rs/pull/38 with a fix

**Comment by hooperben** [comment]
confirmed that fixed it for me - thank you!

**Comment by oblique** [comment]
You can now use this without the patch:

```toml
[dependencies]
celestia-rpc = { git = "https://github.com/eigerco/celestia-node-rs", rev = "1db9f37" }
```

However if you plan to use any other crate from crates.io that depends on tendermint crate (e.g. cosmrs), then you still need the `patch.crates-io` section that I provided above.
